config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get "sign_in" => "devise/sessions#new"
  end


  resources :businesses do
    collection do
      get 'search'
    end
  end

  resources :categories
  resources :contacts, only: [:new, :create]

  get ':id', to: 'categories#show', as: :id

  get 'welcome/index'
  root 'welcome#index'

  get '*path' => redirect('/')
end

app/models/business.rb
class Business < ActiveRecord::Base
  belongs_to :category
  accepts_nested_attributes_for :category

  extend FriendlyId
  friendly_id :name, use: :slugged

  searchkick

  has_attached_file :logo, styles: { large: "500x500", medium: "250x250>", thumb: "150x150#" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

  has_attached_file :audio

    geocoded_by :address
    after_validation :geocode, :if => :address_changed?

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :businesses
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,        :validate => true
  attribute :email,       :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,     :validate => true
  attribute :nickname,    :captcha  => true
  
  def headers
    {
      :subject => "Biz Directory Contact Form",
      :to => "zach.moodie@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]


  def search
    if params[:search].present?
      @businesses = Business.search(params[:search])
    else
      @businesses = Business.all.paginate(page: params[:page], per_page: 6)
    end
  end

  def index
    @businesses = Business.all.paginate(page: params[:page], per_page: 6)
  end

  def new
    @business = Business.new
  end

  def create
    @business = Business.new post_params

    if @business.save
      redirect_to @business, notice: "A new business has been added successfully!"
    else
      render 'new', notice: "Oops. Something went wrong. Try again later."
    end
  end

  def show
    @businesses = Business.all
  end

  def edit
  end

  def update
    if @business.update post_params
      redirect_to @business, notice: "Success! The business info has been updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @business.destroy
    redirect_to businesses_path
  end

  private

  def post_params
    params.require(:business).permit(:name, :address, :city, :postal, :latitude, :longitude, :email, :phone, :url, :description, :keywords, :logo, :audio, :slug, :category_id)
  end

  def find_post
    @business = Business.friendly.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :find_category, only: [:show, :edit, :update, :destroy]

    def index
        @categories = Category.order('name ASC')
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new post_params
        @categories = Category.order('name ASC')

        if @category.save
            redirect_to categories_path, notice: "Your Category has been saved!"
        else
            render 'new', notice: "There was an error while trying to create your category!"
        end

    end

    def show
        @categories = Category.all
    end

    def edit
        category = Category.find(params[:id])
    end

    def update
        if @category.update post_params
            redirect_to @category, notice: "Your Category was successfully updated!"
        else
            render 'edit'
        end
    end

    def destroy
        @category.destroy
        redirect_to categories_path
    end

    private

    def post_params
        params.require(:category).permit(:name)
    end

    def find_category
        @category = Category.find(params[:id])
    end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @businesses = Business.all.paginate(page: params[:page], per_page: 6)
  end

  def show
    @businesses = Business.all
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(content)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_intended_code: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/businesses/_form.html.erb
<%= form_for @business, html: { multipart: true } do |f| %>
	<% if @business.errors.any? %>
		<h2><%= pluralize(@business.errors.count, "error") %> prevented this post from saving:</h2>
		<ul>
			<% @business.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
	<% end %>

	<%= f.label :name %><br>
	<%= f.text_field :name %>

	<br>
	<br>

	<%= f.label :address,  "Address (please include city and province)" %><br>
	<%= f.text_field :address %>

	<br>
	<br>

	<%= f.label :email %><br>
	<%= f.text_field :email %>

	<br>
	<br>

	<%= f.label :phone %><br>
	<%= f.text_field :phone %>

	<br>
	<br>

	<%= f.label :url %><br>
	<%= f.text_field :url %>

	<br>
	<br>

	<%= f.label :description, "Write the business description" %><br>
	<%= f.text_area :description %>

	<br>
	<br>

	<%= f.label :keywords %><br>
	<%= f.text_field :keywords %>

	<br>
	<br>

	<%= f.label :logo %><br>
	<%= f.file_field :logo %>

	<br>
	<br>

	<%= f.label :audio %><br>
	<%= f.file_field :audio %>

	<br>
	<br>

	<%= f.label :category %><br>
	<%= f.collection_select :category_id, Category.all, :id, :name %>

	<br>
	<br>

	<%= f.submit %>

<% end %>

app/views/businesses/edit.html.erb
<h2 id="page_title">Edit '<%= @business.name %>'</h2>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/businesses/index.html.erb
		<h2 id="page_title">Business Listings</h2>

		<div class="wrapper wrapper_padding clearfix">
			<div class="category_wrapper">

				<% @businesses.shuffle.each do |business| %>
					<div class="category_listing clearfix">
						<%= image_tag business.logo.url(:medium), :class => "listing_logo" %>
						<div class="listing_description clearfix">
							<h2><%= link_to business.name, business %></h2>
							<p><%=h truncate(business.description, :length => 200, :separator => ' ') %></p>
							<p><span class="contact_method"><strong>Phone:</strong> <%= business.phone %></span>		<span class="contact_method"><strong>Email:</strong> <%= business.email %></span>		<strong>Website:</strong> <%= link_to business.url, "http://#{business.url}" %></p>
							<%= link_to "More Details", business, class: "button" %>
						</div>
					</div>
					<hr>
				<% end %>


				<%= will_paginate @posts %>
			</div>



			<div class="side_content">
				<div class="bigbox"><%= image_tag("bigBox.jpg", :alt => "Big Box") %></div>
				<h1>Search For A Business</h1>
				<hr>
				<form class="search">
					<p class="category">
						<%= form_for :category do |f| %>
							<%= f.label :category, "Search By Category" %><br>
							<%= f.collection_select :category_id, Category.all.order('name ASC'), :id, :name %>
							<%= button_tag(type: 'submit', class: "button") do %>
								<i class="fa fa-arrow-right"></i>
							<% end %>
						<% end %>
						</form>
							<%= form_tag search_businesses_path, method: :get, role: "search", :class => "search" do %>
								<%= label :category, "Search By Business Name" %>
								<%= text_field_tag :search, params[:search], id: "search", :placeholder => 'Search Business' %>
								<%= button_tag(type: 'submit', class: "button") do %>
									<i class="fa fa-arrow-right"></i>
								<% end %>
							<% end %>
					</p>
				<h1>What Is The Biz Directory?</h1>
				<hr>
				<p>We know how it goes...you hear about a great business on the radio, but you can't quite catch their name or contact information. That's why we developed the Biz Directory!</p>
				<p>This is a way for you to find out more about businesses with great stories, great product and great offers. You'll also find a quick and easy way to contact these places and more!</p>
			</div>
		</div>
	</div>

app/views/businesses/new.html.erb
<h2 id="page_title">Create A Business</h2>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/businesses/search.html.erb
		<h1 id="page_title">Business Listings</h1>

		<div class="wrapper wrapper_padding clearfix">
			<div class="category_wrapper">


				<% @businesses.each do |business| %>
					<div class="category_listing clearfix">
						<%= image_tag business.logo.url(:medium), :class => "listing_logo" %>
						<div class="listing_description clearfix">
							<h2><%= link_to business.name, business %></h2>
							<p><%=h truncate(business.description, :length => 200, :separator => ' ') %></p>
							<p><span class="contact_method"><strong>Phone:</strong> <%= business.phone %></span>		<span class="contact_method"><strong>Email:</strong> <%= business.email %></span>		<strong>Website:</strong> <%= link_to business.url, "http://#{business.url}" %></p>
							<%= link_to "More Details", business, class: "button" %>
						</div>
					</div>
					<hr>
				<% end %>


				<%= will_paginate @posts %>
			</div>



			<div class="side_content">
		        <div class="bigbox"><%= image_tag("bigBox.jpg", :alt => "Big Box") %></div>
		        <h1>Search For A Business</h1>
		        <hr>
		        <form class="search">
		            <p class="category">
						<%= form_for :category do |f| %>
							<%= f.label :category, "Search By Category" %><br>
							<%= f.collection_select :category_id, Category.all.order('name ASC'), :id, :name %>
							<%= button_tag(type: 'submit', class: "button") do %>
								<i class="fa fa-arrow-right"></i>
							<% end %>
						<% end %>
						</form>
							<%= form_tag search_businesses_path, method: :get, role: "search", :class => "search" do %>
								<%= label :category, "Search By Business Name" %>
								<%= text_field_tag :search, params[:search], id: "search", :placeholder => 'Search Business' %>
								<%= button_tag(type: 'submit', class: "button") do %>
									<i class="fa fa-arrow-right"></i>
								<% end %>
							<% end %>
		            </p>
		        <h1>What Is The Biz Directory?</h1>
		        <hr>
		        <p>We know how it goes...you hear about a great business on the radio, but you can't quite catch their name or contact information. That's why we developed the Biz Directory!</p>
		        <p>This is a way for you to find out more about businesses with great stories, great product and great offers. You'll also find a quick and easy way to contact these places and more!</p>
		        <ul class="station_logos">
		            <li><%= link_to image_tag("logo_cisn.png", :alt => "CISN Country 103.9") %></li>
		            <li><a href="http://www.630ched.com" target="_blank"><%= image_tag("logo_ched.png", :alt => "630 CHED") %></a></li>
		            <li><a href="http://www.925freshradio.ca" target="_blank"><%= image_tag("logo_fresh.png", :alt => "925 Fresh Radio") %></a></li>
		            <li><a href="http://www.inews880.com" target="_blank"><%= image_tag("logo_chqt.png", :alt => "iNews 880") %></a></li>
		        </ul>
		    </div>
	</div>
		</div>

app/views/businesses/show.html.erb
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
			<script type="text/javascript">
			            // When the window has finished loading create our google map below
			            google.maps.event.addDomListener(window, 'load', init);
						google.maps.event.addDomListener(window, 'page:load', initialize);

			            function init() {
			                // Basic options for a simple Google Map
			                // For more options see: https://developers.google.com/maps/documentation/javascript/reference#MapOptions
			                var mapOptions = {
			                    // How zoomed in you want the map to start at (always required)
			                    zoom: 13,

			                    // The latitude and longitude to center the map (always required)
			                    center: new google.maps.LatLng(<%= @business.latitude %>, <%= @business.longitude %>),

													// Disable default map options
													disableDefaultUI: true,

			                    // How you would like to style the map.
			                    // This is where you would paste any style found on Snazzy Maps.
			                    styles: [{"featureType":"water","stylers":[{"visibility":"on"},{"color":"#b5cbe4"}]},{"featureType":"landscape","stylers":[{"color":"#efefef"}]},{"featureType":"road.highway","elementType":"geometry","stylers":[{"color":"#83a5b0"}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#bdcdd3"}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#ffffff"}]},{"featureType":"poi.park","elementType":"geometry","stylers":[{"color":"#e3eed3"}]},{"featureType":"administrative","stylers":[{"visibility":"on"},{"lightness":33}]},{"featureType":"road"},{"featureType":"poi.park","elementType":"labels","stylers":[{"visibility":"on"},{"lightness":20}]},{},{"featureType":"road","stylers":[{"lightness":20}]}]
			                };

			                // Get the HTML DOM element that will contain your map
			                // We are using a div with id="map" seen below in the <body>
			                var mapElement = document.getElementById('map');

			                // Create the Google Map using our element and options defined above
			                var map = new google.maps.Map(mapElement, mapOptions);

			                // Let's also add a marker while we're at it
								var image = '<%= asset_path 'map_pin.png' %>';
			                	var marker = new google.maps.Marker({
			                    position: new google.maps.LatLng(<%= @business.latitude %>, <%= @business.longitude %>),
			                    map: map,
								icon: image,
			                    title: '<%= @business.name %>'
			                });
			            }
			        </script>
		</header>

		<h2 id="page_title"><%= @business.name %></h2>

		<div class="wrapper wrapper_padding business clearfix">

			<div class="col-1 contact_info business_content">
				<%= image_tag @business.logo.url(:medium), :class => "business_logo" %>
				<h3 class="location"><%= @business.address %></h3>
				Phone: <%= @business.phone %><br>
				Email: <%= @business.email %><br>
				Website: <%= link_to @business.url, "http://#{@business.url}" %><br>
				<hr>
				<h6>Listen To Our Latest Commercial</h6>
				<audio controls>
					<source src="<%= @business.audio %>" type="audio/mpeg">
					Your browser does not support the audio element.
				</audio>
			</div>

			<div class="col-2 business_content">
				<h2>About Us</h2>
				<hr>
				<p><%= markdown @business.description %></p>
				<% if user_signed_in? %>
					<div id="admin_links">
						<%= link_to "Edit Business", edit_business_path(@business) %>
						<%= link_to "Delete Business", business_path(@business), method: :delete, data: { confirm: "Are you sure you want to delete this business?" } %>
					</div>
				<% end %>
			</div>

			<div class="col-3 search business_content">
				<h1>Search For A Business</h1>
				<hr>
				<form class="search">
					<p class="category">
						<%= form_for :category do |f| %>
							<%= f.label :category, "Search By Category" %><br>
							<%= f.collection_select :category_id, Category.all.order('name ASC'), :id, :name %>
							<%= button_tag(type: 'submit', class: "button") do %>
								<i class="fa fa-arrow-right"></i>
							<% end %>
						<% end %>
						</form>
							<%= form_tag search_businesses_path, method: :get, role: "search", :class => "search" do %>
								<%= label :category, "Search By Business Name" %>
								<%= text_field_tag :search, params[:search], id: "search", :placeholder => 'Search Business' %>
								<%= button_tag(type: 'submit', class: "button") do %>
									<i class="fa fa-arrow-right"></i>
								<% end %>
							<% end %>
					</p>

			</div>
		</div>

		<div id="map"></div>

app/views/categories/_form.html.erb
<%= form_for :category do |f| %>

	<%= f.label :category %><br>
	<%= f.text_field :name %>

	<br>
	<br>

	<%= f.submit %>

<% end %>

app/views/categories/edit.html.erb
<h2 id="page_title">Edit '<%= @category.name %>'</h2>

<div class="skinny_wrapper wrapper_padding">
	<%= form_for (@category) do |f| %>

		<%= f.label :category %><br>
		<%= f.text_field :name %>

		<br>
		<br>

		<%= f.submit %>

	<% end %>
</div>

app/views/categories/index.html.erb
<h2 id="page_title">Add A Category</h2>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

<h2 id="page_title">Edit A Category</h2>

<div class="skinny_wrapper wrapper_padding">
	<% @categories.each do |category| %>
		<h2><%= link_to category.name, category, :class => "categoryListing" %></h2>
	<% end %>
</div>

app/views/categories/show.html.erb
<h2 id="page_title"><%= @category.name %></h2>

<div class="skinny_wrapper wrapper_padding">
    <% if user_signed_in? %>
        <div id="admin_links">
            <%= link_to "Edit Category", edit_category_path(@category) %>
            <%= link_to "Delete Category", category_path(@category), method: :delete, data: { confirm: "Are you sure you want to delete this category?" } %>
        </div>
    <% end %>
</div>

app/views/contacts/create.html.erb
<h1 id="page_title">Advertise With Us!</h1>

<div class="skinny_wrapper clearfix">
	<h1>Thank you for you message.</h1>
	<p>I'll get back to you soon!</p>
</div>

app/views/contacts/new.html.erb
<h2 id="page_title">Advertise With Us</h2>

<div class="skinny_wrapper wrapper_padding">
	<%= form_for @contact do |f| %>
		<%= f.label :name %><br>
		<%= f.text_field :name, required: true %>

		<br>

		<%= f.label :email %><br>
		<%= f.text_field :email, required: true %>

		<br>

		<%= f.label :message %><br>
		<%= f.text_area :message, as: :text %>

		<div class="hidden">
			<%= f.label :nickname %><br>
			<%= f.text_field :nickname, hint: 'leave this field blank' %>
		</div>

		<%= f.submit 'Send Message', class: "button" %>
	<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>The Edmonton Biz Directory | Corus Radio Edmonton</title>
	<link href='https://fonts.googleapis.com/css?family=Raleway:400,500,600,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header id= "main_navigation" class="clearfix">
	<div id="leftHeader">
		<%= link_to image_tag('logo_biz.png'), root_path, :class => "main_logo" %>
		<%= yield :logo %>
	</div>
	<div id="rightHeader">
		<nav>
			<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Business Listings", businesses_path %></li>
			<% if user_signed_in? %>
				<li><a href="#">Admin</a>
						<ul>
					    	<li><%= link_to "Add A Business", new_business_path %></li>
					    	<li><%= link_to "Manage Categories", categories_path %></li>
					    </ul>
				</li>
				<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
			<% end %>
			<li><%= link_to "Get In Contact", new_contact_path, class: "button" %></li>
		</nav>
		<%= yield :homeNav %>
	</div>
</header>

<% if notice %>
	<p class="notice"><%= notice %></p>
<% elsif alert %>
	<p class="alert"><%= alert %></p>
<% end %>

<%= yield %>

<footer id="main_footer">
	<p class="copyright">
		<h6>Corus Radio</h6>
		Copyright &copy; 2016  |  All Rights Reserved
	</p>
</footer>
</body>
</html>

app/views/welcome/index.html.erb
<% content_for :logo do %>
	<%= link_to image_tag('logo_biz_light.png'), root_path %>
	<style>
		body {
			background-image: url(/assets/mainBG.jpg);
			background-repeat: no-repeat;
			background-position: top;
			-ms-background-size: contain;
			-o-background-size: contain;
			-moz-background-size: contain;
			-webkit-background-size: contain;
			background-size: contain;
		}
		.main_logo {
			display: none;
		}
		nav {
			font-weight: 400!important;
		}
		nav ul li  a {
			color: #fff!important;
		}
		nav ul li a:hover {
			color: #2abda8!important;
		}
		nav .button:hover {
			color: #fff!important;
		}

	</style>
<% end %>



<div class="jumbotron">
	<h1>HEAR SOMETHING YOU LIKED?</h1>
	<h2>Find out more about our advertisers and get in contact with<br />
them fast with the Edmonton Business Directory!</h2>
	<div class="header_search">
		<%= form_tag search_businesses_path, method: :get, role: "search" do %>
			<p>
				<%= text_field_tag :search, params[:search], id: "search", :placeholder => 'Search Our Listings By Business Name' %>
				<%= button_tag(type: 'submit', class: "button") do %>
					<i class="fa fa-search"></i>
				<% end %>
			</p>
		<% end %>
	</div>
</div>

<section id="content">
    <div class="wrapper clearfix">

    <div class="main_content">
		<h1>Business Listings</h1>
		<hr>
		<% @businesses.shuffle.each do |business| %>
			<div class="category_listing clearfix">
				<%= image_tag business.logo.url(:medium), :class => "listing_logo" %>
				<div class="listing_description">
					<h2><%= link_to business.name, business %></h2>
					<p><%=h truncate(business.description, :length => 200, :separator => ' ') %></p>
					<p><span class="contact_method"><strong>Phone:</strong> <%= business.phone %></span><span class="contact_method"><strong>Email:</strong> <%= business.email %></span>		<strong>Website:</strong> <%= link_to business.url, "http://#{business.url}" %></p>
					<%= link_to "More Details", business, class: "button" %>
				</div>
			</div>
			<br>
			<hr class="hr_wide">
		<% end %>

		<%= will_paginate @businesses %>

    </div>

    <div class="side_content">
        <div class="bigbox"><%= image_tag("bigBox.jpg", :alt => "Big Box") %></div>
        <h1>Search For A Business</h1>
        <hr>
        <form class="search">
            <p class="category">
				<%= form_for :category do |f| %>
					<%= f.label :category, "Search By Category" %><br>
					<%= f.collection_select :category_id, Category.all.order('name ASC'), :id, :name %>
					<%= button_tag(type: 'submit', class: "button") do %>
						<i class="fa fa-arrow-right"></i>
					<% end %>
				<% end %>
				</form>
					<%= form_tag search_businesses_path, method: :get, role: "search", :class => "search" do %>
						<%= label :category, "Search By Business Name" %>
						<%= text_field_tag :search, params[:search], id: "search", :placeholder => 'Search Business' %>
						<%= button_tag(type: 'submit', class: "button") do %>
							<i class="fa fa-arrow-right"></i>
						<% end %>
					<% end %>
            </p>
        <h1>What Is The Biz Directory?</h1>
        <hr>
        <p>We know how it goes...you hear about a great business on the radio, but you can't quite catch their name or contact information. That's why we developed the Biz Directory!</p>
        <p>This is a way for you to find out more about businesses with great stories, great product and great offers. You'll also find a quick and easy way to contact these places and more!</p>
        <ul class="station_logos">
            <li><%= link_to image_tag("logo_cisn.png", :alt => "CISN Country 103.9") %></li>
            <li><a href="http://www.630ched.com" target="_blank"><%= image_tag("logo_ched.png", :alt => "630 CHED") %></a></li>
            <li><a href="http://www.925freshradio.ca" target="_blank"><%= image_tag("logo_fresh.png", :alt => "925 Fresh Radio") %></a></li>
            <li><a href="http://www.inews880.com" target="_blank"><%= image_tag("logo_chqt.png", :alt => "iNews 880") %></a></li>
        </ul>
    </div>

    </div>
</section>